//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace демо0202
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialsInProducts
    {
        public int Код { get; set; }
        public Nullable<int> Материал { get; set; }
        public Nullable<int> Количество { get; set; }
        public Nullable<int> Продукция { get; set; }
    
        public virtual Materials Materials { get; set; }
        public virtual Products Products { get; set; }
    }
}
