//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace демо0202
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partners
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Partners()
        {
            this.Orders = new HashSet<Orders>();
        }
    
        public int Код { get; set; }
        public Nullable<int> Тип_партнера { get; set; }
        public string Наименование_партнера { get; set; }
        public string Фамилия_директора { get; set; }
        public string Имя_директора { get; set; }
        public string НомерТелефона { get; set; }
        public string Отчество_директора { get; set; }
        public string Юридический_адрес_партнера { get; set; }
        public string ИНН { get; set; }
        public Nullable<int> Рейтинг { get; set; }
        public string Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual PartnesType PartnesType { get; set; }
    }
}
