//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace демо0202
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.MaterialsInProducts = new HashSet<MaterialsInProducts>();
            this.ProductsInOrders = new HashSet<ProductsInOrders>();
        }
    
        public int Код { get; set; }
        public Nullable<int> Тип_продукции { get; set; }
        public string Наименование_продукции { get; set; }
        public string Артикул { get; set; }
        public Nullable<double> Минимальная_стоимость_для_партнера { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialsInProducts> MaterialsInProducts { get; set; }
        public virtual ProductsType ProductsType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductsInOrders> ProductsInOrders { get; set; }
    }
}
